//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ChiTietHDs = new HashSet<ChiTietHD>();
        }
    
        public int MaSP { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public string TenSP { get; set; }
        public string DVT { get; set; }
        public string NoiSanXuat { get; set; }
        public double GiaNhap { get; set; }
        public double GiaBan { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public byte[] HinhAnh { get; set; }
    
        public virtual ICollection<ChiTietHD> ChiTietHDs { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
    }
}
